package com.gigbiz.app;

import android.app.*;
import android.os.Bundle;
import android.graphics.*;
import android.graphics.pdf.PdfDocument;
import java.io.OutputStream;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.content.*;
import android.net.Uri;
import android.provider.MediaStore;
import java.io.InputStream;
import android.widget.*;
import com.google.firebase.auth.*;
import com.google.firebase.firestore.*;
import com.google.firebase.storage.*;
import java.util.*;
import java.net.URLEncoder;

public class MainActivity extends Activity {
 FirebaseAuth auth; FirebaseFirestore db; FirebaseStorage storage; ImageView workerPhotoView; static final int PICK_WORKER_PHOTO=713;
 int purple=Color.rgb(109,58,190), purple2=Color.rgb(133,74,214), green=Color.rgb(38,198,112), dark=Color.rgb(27,43,52), muted=Color.rgb(105,113,122), bg=Color.rgb(249,250,252), white=Color.WHITE;
 int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
 TextView tv(String s,float z,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(dark);t.setTypeface(Typeface.DEFAULT,b?Typeface.BOLD:Typeface.NORMAL);t.setPadding(dp(7),dp(5),dp(7),dp(5));return t;}
 GradientDrawable bg(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
 GradientDrawable stroke(int color,int line,int radius){GradientDrawable g=bg(white,radius);g.setStroke(dp(line),color);return g;}
 TextView button(String s,int color){TextView t=tv(s,14,true);t.setGravity(Gravity.CENTER);t.setTextColor(white);t.setBackground(bg(color,10));return t;}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 LinearLayout base(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setBackgroundColor(bg);return l;}
 void add(LinearLayout p,View v,int h,int top){LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,dp(h));q.topMargin=dp(top);p.addView(v,q);}
 @Override public void onCreate(Bundle b){super.onCreate(b);auth=FirebaseAuth.getInstance();db=FirebaseFirestore.getInstance();storage=FirebaseStorage.getInstance();if(auth.getCurrentUser()==null)login();else boot();}
 void login(){LinearLayout r=base();r.setGravity(Gravity.CENTER);r.setPadding(dp(24),dp(20),dp(24),dp(20));ImageView logo=new ImageView(this);logo.setImageResource(com.gigbiz.app.R.drawable.ic_gigbiz);logo.setScaleType(ImageView.ScaleType.FIT_CENTER);r.addView(logo,new LinearLayout.LayoutParams(dp(100),dp(100)));TextView h=tv("GigSathi",32,true);h.setGravity(Gravity.CENTER);r.addView(h,new LinearLayout.LayoutParams(-1,dp(60)));TextView s=tv("Earn • Work • Grow",17,false);s.setGravity(Gravity.CENTER);r.addView(s,new LinearLayout.LayoutParams(-1,dp(40)));EditText e=field("Email"),p=field("Password");p.setInputType(0x81);add(r,e,54,10);add(r,p,54,10);TextView b=button("LOGIN",purple);add(r,b,54,18);TextView n=tv("New worker? Create account",15,true);n.setGravity(Gravity.CENTER);add(r,n,45,8);TextView m=tv("Team Member Login / Register",15,true);m.setTextColor(purple);m.setGravity(Gravity.CENTER);add(r,m,48,4);b.setOnClickListener(v->{auth.signInWithEmailAndPassword(e.getText().toString().trim(),p.getText().toString()).addOnCompleteListener(x->{if(x.isSuccessful())boot();else toast(err(x.getException()));});});n.setOnClickListener(v->signup());m.setOnClickListener(v->memberAuthScreen(false));setContentView(r);}
 EditText field(String h){EditText e=new EditText(this);e.setHint(h);e.setSingleLine(true);e.setTextSize(15);e.setPadding(dp(14),0,dp(14),0);e.setBackground(stroke(Color.rgb(220,225,232),1,11));return e;}
 void signup(){LinearLayout r=base();r.setPadding(dp(22),dp(28),dp(22),dp(20));TextView h=tv("Create your GigSathi account",26,true);h.setGravity(Gravity.CENTER);add(r,h,65,0);EditText n=field("Full name"),e=field("Email"),ph=field("Mobile number"),sk=field("Skills"),loc=field("City / Location"),pw=field("Password (6+)");pw.setInputType(0x81);for(EditText x:new EditText[]{n,e,ph,sk,loc,pw})add(r,x,53,8);TextView b=button("CREATE ACCOUNT",purple);add(r,b,53,18);b.setOnClickListener(v->{auth.createUserWithEmailAndPassword(e.getText().toString().trim(),pw.getText().toString()).addOnCompleteListener(x->{if(!x.isSuccessful()){toast(err(x.getException()));return;}Map<String,Object> m=new HashMap<>();m.put("name",n.getText().toString().trim());m.put("email",e.getText().toString().trim());m.put("phone",ph.getText().toString().trim());m.put("skills",sk.getText().toString().trim());m.put("location",loc.getText().toString().trim());m.put("role","worker");m.put("wallet",0);m.put("status","active");m.put("createdAt",FieldValue.serverTimestamp());db.collection("users").document(auth.getCurrentUser().getUid()).set(m).addOnSuccessListener(z->boot()).addOnFailureListener(q->toast(err(q)));});});setContentView(r);}
 
 void memberAuthScreen(boolean unused){
  LinearLayout r=base();r.setGravity(Gravity.CENTER);r.setPadding(dp(22),dp(20),dp(22),dp(24));
  TextView h=tv("GigSathi Team Member",26,true);h.setGravity(Gravity.CENTER);add(r,h,62,0);
  TextView hint=tv("Login with the email invited by your Team Owner. New members must use the same invited email.",14,false);hint.setGravity(Gravity.CENTER);add(r,hint,75,4);
  EditText email=field("Invited email address"),pass=field("Password");pass.setInputType(0x81);add(r,email,54,8);add(r,pass,54,8);
  TextView loginBtn=button("TEAM MEMBER LOGIN",purple);add(r,loginBtn,54,16);
  TextView reg=tv("First time? Activate your team account",14,true);reg.setTextColor(purple);reg.setGravity(Gravity.CENTER);add(r,reg,48,8);
  TextView back=tv("← Back to login",14,true);back.setGravity(Gravity.CENTER);add(r,back,42,4);
  loginBtn.setOnClickListener(v->{String em=email.getText().toString().trim().toLowerCase(Locale.ROOT),pw=pass.getText().toString();if(em.isEmpty()||pw.isEmpty()){toast("Enter email and password.");return;}auth.signInWithEmailAndPassword(em,pw).addOnCompleteListener(x->{if(x.isSuccessful())boot();else toast(err(x.getException()));});});
  reg.setOnClickListener(v->memberSignupScreen());back.setOnClickListener(v->login());setContentView(r);
 }
 void memberSignupScreen(){
  LinearLayout r=base();r.setPadding(dp(20),dp(18),dp(20),dp(20));TextView h=tv("Activate Team Member Account",24,true);h.setGravity(Gravity.CENTER);add(r,h,65,0);
  EditText name=field("Full name"),email=field("Invited email (same as owner added)"),phone=field("Mobile number"),pass=field("Create password (6+ characters)");pass.setInputType(0x81);
  for(EditText e:new EditText[]{name,email,phone,pass})add(r,e,53,8);
  TextView save=button("ACTIVATE ACCOUNT",purple);add(r,save,54,18);TextView back=tv("← Back",14,true);back.setGravity(Gravity.CENTER);add(r,back,42,8);back.setOnClickListener(v->memberAuthScreen(false));
  save.setOnClickListener(v->{String n=name.getText().toString().trim(),em=email.getText().toString().trim().toLowerCase(Locale.ROOT),ph=phone.getText().toString().trim(),pw=pass.getText().toString();if(n.length()<2||!emValid(em)||ph.replaceAll("\\D","").length()<10||pw.length()<6){toast("Enter valid name, invited email, mobile and 6+ character password.");return;}
   auth.createUserWithEmailAndPassword(em,pw).addOnCompleteListener(created->{if(!created.isSuccessful()){toast(err(created.getException()));return;}String uid=auth.getCurrentUser().getUid();
    db.collection("teamMembers").whereEqualTo("email",em).get().addOnSuccessListener(invites->{if(invites.isEmpty()){auth.getCurrentUser().delete();toast("Invitation not found. Ask your Team Owner to add this email first.");return;}DocumentSnapshot invite=invites.getDocuments().get(0);String owner=invite.getString("ownerId");if(owner==null||owner.isEmpty()){auth.getCurrentUser().delete();toast("This invitation is invalid. Ask your Team Owner to add you again.");return;}
     if("active".equals(invite.getString("status"))&&invite.getString("memberUid")!=null){auth.getCurrentUser().delete();toast("This invitation has already been activated. Please log in.");return;}
     Map<String,Object> user=new HashMap<>();user.put("name",n);user.put("email",em);user.put("phone",ph);user.put("role","member");user.put("ownerId",owner);user.put("wallet",0);user.put("status","active");user.put("createdAt",FieldValue.serverTimestamp());
     db.collection("users").document(uid).set(user).addOnSuccessListener(done->db.collection("teamMembers").document(invite.getId()).update("memberUid",uid,"status","active","activatedAt",FieldValue.serverTimestamp()).addOnSuccessListener(z->boot()).addOnFailureListener(ex->{toast("Account created but invitation link update failed: "+err(ex));})).addOnFailureListener(ex->{toast("Unable to save member profile: "+err(ex));});
    }).addOnFailureListener(ex->{toast("Unable to verify invitation: "+err(ex));});
   });
  });setContentView(r);
 }
 void memberHome(DocumentSnapshot u){
  LinearLayout root=base();ScrollView scroll=new ScrollView(this);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(12),dp(16),dp(24));scroll.addView(c);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  String name=u.getString("name");if(name==null)name="Team Member";
  TextView brand=tv("GigSathi • TEAM WORKSPACE",13,true);brand.setTextColor(purple);c.addView(brand);
  TextView welcome=tv("Hello, "+name,25,true);add(c,welcome,52,6);
  TextView summary=tv("Complete assigned tasks, submit customer leads and track your earnings.",14,false);c.addView(summary);
  double wallet=0;Object w=u.get("wallet");if(w instanceof Number)wallet=((Number)w).doubleValue();
  TextView balance=tv("YOUR EARNINGS\n₹"+wallet,22,true);balance.setTextColor(green);balance.setPadding(dp(16),dp(14),dp(16),dp(14));balance.setBackground(stroke(Color.rgb(215,222,228),1,14));add(c,balance,92,14);
  TextView tasks=button("MY ASSIGNED TASKS",purple);add(c,tasks,54,14);tasks.setOnClickListener(v->memberTasksScreen());
  TextView leads=button("MY CUSTOMER LEADS",purple2);add(c,leads,54,9);leads.setOnClickListener(v->memberLeadsScreen());
  TextView submit=button("＋ SUBMIT CUSTOMER LEAD",green);add(c,submit,54,9);submit.setOnClickListener(v->leadSubmitScreen(null));
  TextView withdraw=button("WITHDRAW EARNINGS",purple);add(c,withdraw,54,9);withdraw.setOnClickListener(v->withdrawScreen());
  TextView refresh=button("REFRESH",dark);add(c,refresh,48,9);refresh.setOnClickListener(v->boot());
  TextView out=tv("LOG OUT",14,true);out.setGravity(Gravity.CENTER);add(c,out,46,8);out.setOnClickListener(v->{auth.signOut();login();});
  root.addView(bottomNavMember(),new LinearLayout.LayoutParams(-1,dp(65)));setContentView(root);
 }
 View bottomNavMember(){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);n.setBackground(bg(white,16));String[] labels={"⌂\nHome","✓\nTasks","＋\nLead","₹\nWithdraw"};for(int i=0;i<labels.length;i++){final int k=i;TextView b=tv(labels[i],12,true);b.setGravity(Gravity.CENTER);b.setTextColor(purple);n.addView(b,new LinearLayout.LayoutParams(0,dp(60),1));b.setOnClickListener(v->{if(k==0)boot();else if(k==1)memberTasksScreen();else if(k==2)leadSubmitScreen(null);else withdrawScreen();});}return n;}
 void memberTasksScreen(){
  String uid=auth.getCurrentUser().getUid();LinearLayout r=base();topBar(r,"My Assigned Tasks");ScrollView s=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(dp(14),dp(8),dp(14),dp(24));s.addView(list);r.addView(s);
  db.collection("tasks").whereEqualTo("memberId",uid).get().addOnSuccessListener(q->{if(q.isEmpty())list.addView(tv("No tasks assigned yet. Your Team Owner/Admin can assign tasks from the Admin panel.",14,false));for(DocumentSnapshot d:q){String status=d.getString("status");if(status==null)status="pending";LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(10),dp(12),dp(10));card.setBackground(stroke(Color.rgb(225,229,235),1,12));card.addView(tv(String.valueOf(d.get("title")==null?"Assigned Task":d.get("title")),17,true));card.addView(tv(String.valueOf(d.get("description")==null?"":d.get("description")),14,false));card.addView(tv("Status: "+status,13,true));if(!"completed".equals(status)){TextView done=button("MARK AS COMPLETED",green);add(card,done,44,8);String id=d.getId();done.setOnClickListener(v->db.collection("tasks").document(id).update("status","completed","completedBy",uid,"completedAt",FieldValue.serverTimestamp()).addOnSuccessListener(z->{toast("Task marked completed.");memberTasksScreen();}).addOnFailureListener(e->toast(err(e))));}list.addView(card,new LinearLayout.LayoutParams(-1,-2));}}).addOnFailureListener(e->toast(err(e)));setContentView(r);
 }
 void memberLeadsScreen(){
  String uid=auth.getCurrentUser().getUid();LinearLayout r=base();topBar(r,"My Customer Leads");ScrollView s=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(dp(14),dp(8),dp(14),dp(24));s.addView(list);r.addView(s);
  TextView add=button("＋ SUBMIT LEAD",purple);add(list,add,50,8);add.setOnClickListener(v->leadSubmitScreen(null));
  db.collection("leads").whereEqualTo("memberId",uid).get().addOnSuccessListener(q->{if(q.isEmpty())list.addView(tv("No leads submitted yet.",14,false));for(DocumentSnapshot d:q){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(10),dp(12),dp(10));card.setBackground(stroke(Color.rgb(225,229,235),1,12));card.addView(tv(String.valueOf(d.get("customerName")==null?"Customer":d.get("customerName")),16,true));card.addView(tv(String.valueOf(d.get("gigTitle")==null?"":d.get("gigTitle")),13,false));card.addView(tv("Status: "+String.valueOf(d.get("status")==null?"pending":d.get("status")),13,true));card.addView(tv("Potential earning: ₹"+String.valueOf(d.get("taskAmount")==null?"0":d.get("taskAmount")),13,false));if(Boolean.TRUE.equals(d.getBoolean("walletCredited")))card.addView(tv("✓ Earning credited",12,true));list.addView(card,new LinearLayout.LayoutParams(-1,-2));}}).addOnFailureListener(e->toast(err(e)));setContentView(r);
 }

 void boot(){db.collection("users").document(auth.getCurrentUser().getUid()).get().addOnSuccessListener(d->{String role=d.getString("role");if("worker".equals(role))home(d);else if("member".equals(role)){if(!"active".equals(d.getString("status"))){auth.signOut();toast("Team member account is pending Admin/Team Owner approval.");login();}else memberHome(d);}else{auth.signOut();toast("Worker or Team Member account required.");login();}}).addOnFailureListener(e->toast(err(e)));}
 void home(DocumentSnapshot u){
  LinearLayout root=base();root.setBackgroundColor(Color.rgb(250,250,250));ScrollView scroll=new ScrollView(this);LinearLayout c=new LinearLayout(this);c.setOrientation(1);c.setPadding(dp(14),dp(8),dp(14),dp(22));scroll.addView(c);
  LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);
  LinearLayout prof=new LinearLayout(this);prof.setOrientation(1);prof.setGravity(Gravity.CENTER);TextView av=tv("●",25,true);av.setTextColor(Color.rgb(25,126,230));prof.addView(av);String nm=u.getString("name");if(nm==null||nm.isEmpty())nm="Adviser";TextView name=tv(nm.toUpperCase(Locale.ROOT),12,true);name.setGravity(Gravity.CENTER);prof.addView(name);header.addView(prof,new LinearLayout.LayoutParams(0,dp(70),1));prof.setOnClickListener(v->profileScreen());
  View community=quickHeaderItem("●","Community",Color.rgb(39,174,96));header.addView(community,new LinearLayout.LayoutParams(0,dp(70),1));community.setOnClickListener(v->helpSupport());View connect=quickHeaderItem("➤","Connect",Color.rgb(20,130,230));header.addView(connect,new LinearLayout.LayoutParams(0,dp(70),1));connect.setOnClickListener(v->db.collection("users").document(auth.getCurrentUser().getUid()).get().addOnSuccessListener(this::shareProfile));View earn=quickHeaderItem("₹","Earnings",Color.rgb(20,130,230));header.addView(earn,new LinearLayout.LayoutParams(0,dp(70),1));earn.setOnClickListener(v->withdrawScreen());c.addView(header);
  LinearLayout banner=new LinearLayout(this);banner.setOrientation(1);banner.setPadding(dp(18),dp(14),dp(14),dp(12));banner.setBackground(bg(Color.rgb(15,57,112),16));TextView tag=tv("GIGSATHI • WORK & EARN",12,true);tag.setTextColor(Color.rgb(255,202,54));banner.addView(tag);TextView title=tv("Earn more with\nGigSathi Projects",25,true);title.setTextColor(white);add(banner,title,-2,5);TextView sub=tv("Discover projects • Refer customers • Get rewarded",12,false);sub.setTextColor(Color.rgb(238,244,255));banner.addView(sub);TextView go=button("EXPLORE PROJECTS  →",Color.rgb(230,35,57));add(banner,go,42,8);go.setOnClickListener(v->gigsScreen());LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(190));bp.setMargins(0,dp(8),0,dp(16));c.addView(banner,bp);
  LinearLayout money=new LinearLayout(this);View pending=moneyCard("Pending","₹ "+String.format(Locale.US,"%.2f",numberVal(u.get("pendingEarnings"))),Color.rgb(250,235,229),Color.rgb(54,128,220),"⌛");LinearLayout.LayoutParams a=new LinearLayout.LayoutParams(0,dp(82),1);a.setMargins(0,0,dp(5),0);money.addView(pending,a);pending.setOnClickListener(v->leadsScreen());View paid=moneyCard("Paid","₹ "+String.format(Locale.US,"%.2f",numberVal(u.get("paidEarnings"))),Color.rgb(226,249,222),Color.rgb(36,150,70),"✓");LinearLayout.LayoutParams b=new LinearLayout.LayoutParams(0,dp(82),1);b.setMargins(dp(5),0,0,0);money.addView(paid,b);paid.setOnClickListener(v->withdrawScreen());c.addView(money);
  sectionTitle(c,"Popular projects","See all",v->gigsScreen());LinearLayout projects=new LinearLayout(this);HorizontalScrollView ph=new HorizontalScrollView(this);ph.setHorizontalScrollBarEnabled(false);ph.addView(projects);c.addView(ph,new LinearLayout.LayoutParams(-1,dp(155)));
  db.collection("gigs").whereEqualTo("status","active").limit(10).get().addOnSuccessListener(q->{if(q.isEmpty()){projects.addView(projectCard("Kotak 811","₹420","K",Color.rgb(208,31,53)));projects.addView(projectCard("Choice","₹250","✕",Color.rgb(54,49,150)));projects.addView(projectCard("Banking Project","₹300","₹",purple));}else for(DocumentSnapshot d:q){String t=d.getString("title");if(t==null)t="Project";View card=projectCard(t,"₹"+String.valueOf(d.get("pay")==null?"0":d.get("pay")),"₹",purple);card.setOnClickListener(v->gigDetail(d));projects.addView(card);}});
  sectionTitle(c,"All categories","View all",v->workCategoriesScreen());String[][] cats={{"▣","Credit Card"},{"▥","Demat Account"},{"▤","Savings Account"},{"▧","BNPL"},{"♙","Investment Account"},{"↗","UPI"},{"▦","Business Account"},{"♧","Personal Loan"},{"₹","Insurance"},{"▣","Mobile & DTH"},{"▥","Bank Account"},{"✓","Other Services"}};
  for(int row=0;row<3;row++){LinearLayout gr=new LinearLayout(this);gr.setOrientation(0);for(int col=0;col<4;col++){String[] item=cats[row*4+col];View tile=categoryTile(item[0],item[1]);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(122),1);p.setMargins(dp(2),dp(3),dp(2),dp(5));gr.addView(tile,p);tile.setOnClickListener(v->categoryItemsScreen(item[1]));}c.addView(gr);}
  TextView team=button("MY TEAM  •  ADD / MANAGE MEMBERS",purple);add(c,team,52,12);team.setOnClickListener(v->teamScreen());TextView training=button("VIEW TRAININGS",purple2);add(c,training,50,8);training.setOnClickListener(v->trainingScreen());root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));root.addView(bottomNav(),new LinearLayout.LayoutParams(-1,dp(68)));setContentView(root);
 }
 double numberVal(Object o){return o instanceof Number?((Number)o).doubleValue():0.0;}
 View quickHeaderItem(String symbol,String label,int color){LinearLayout x=new LinearLayout(this);x.setOrientation(1);x.setGravity(Gravity.CENTER);TextView i=tv(symbol,23,true);i.setTextColor(color);i.setGravity(Gravity.CENTER);i.setBackground(bg(Color.rgb(242,246,252),50));x.addView(i,new LinearLayout.LayoutParams(dp(40),dp(40)));TextView t=tv(label,12,true);t.setGravity(Gravity.CENTER);x.addView(t);return x;}
 View moneyCard(String label,String value,int color,int accent,String symbol){LinearLayout x=new LinearLayout(this);x.setGravity(Gravity.CENTER_VERTICAL);x.setPadding(dp(10),dp(8),dp(8),dp(8));x.setBackground(stroke(color,1,16));LinearLayout l=new LinearLayout(this);l.setOrientation(1);l.addView(tv(label,14,false));TextView val=tv(value,16,true);val.setTextColor(Color.BLACK);l.addView(val);x.addView(l,new LinearLayout.LayoutParams(0,-2,1));TextView icon=tv(symbol,20,true);icon.setTextColor(accent);x.addView(icon);return x;}
 View projectCard(String title,String pay,String symbol,int color){LinearLayout x=new LinearLayout(this);x.setOrientation(1);x.setGravity(Gravity.CENTER);x.setPadding(dp(8),dp(8),dp(8),dp(8));x.setBackground(stroke(white,1,16));x.setElevation(dp(2));TextView icon=tv(symbol,27,true);icon.setTextColor(color);icon.setGravity(Gravity.CENTER);x.addView(icon,new LinearLayout.LayoutParams(-1,dp(42)));TextView t=tv(title,14,true);t.setGravity(Gravity.CENTER);t.setMaxLines(2);x.addView(t,new LinearLayout.LayoutParams(-1,dp(38)));TextView price=tv(pay,15,true);price.setTextColor(white);price.setGravity(Gravity.CENTER);price.setBackground(bg(Color.rgb(244,183,47),12));add(x,price,32,4);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(160),dp(140));p.setMargins(dp(2),dp(4),dp(10),dp(6));x.setLayoutParams(p);return x;}
 View categoryTile(String symbol,String label){LinearLayout x=new LinearLayout(this);x.setOrientation(1);x.setGravity(Gravity.CENTER);x.setPadding(dp(3),dp(8),dp(3),dp(6));x.setBackground(stroke(white,1,15));x.setElevation(dp(2));TextView i=tv(symbol,24,true);i.setTextColor(Color.rgb(35,126,223));i.setGravity(Gravity.CENTER);i.setBackground(bg(Color.rgb(220,235,255),50));LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(dp(44),dp(44));ip.bottomMargin=dp(6);x.addView(i,ip);TextView t=tv(label,12,true);t.setGravity(Gravity.CENTER);t.setMaxLines(2);x.addView(t,new LinearLayout.LayoutParams(-1,dp(36)));return x;}
View stat(String value,String label,int color){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setGravity(Gravity.CENTER);x.setBackground(stroke(Color.rgb(232,234,239),1,14));TextView a=tv(value,19,true);a.setTextColor(color);a.setGravity(Gravity.CENTER);x.addView(a);TextView b=tv(label,11,false);b.setTextColor(muted);b.setGravity(Gravity.CENTER);x.addView(b);return x;}
 void sectionTitle(LinearLayout c,String a,String b,View.OnClickListener l){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView x=tv(a,18,true);x.setTextColor(dark);r.addView(x,new LinearLayout.LayoutParams(0,dp(54),1));if(!b.isEmpty()){TextView y=tv(b,13,true);y.setTextColor(purple);r.addView(y,new LinearLayout.LayoutParams(dp(65),dp(45)));if(l!=null)y.setOnClickListener(l);}c.addView(r);}
 View serviceCard(String title,String desc,String icon,int color){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(14),dp(10),dp(10),dp(8));x.setBackground(bg(white,14));TextView i=tv(icon,22,true);i.setTextColor(color);x.addView(i);x.addView(tv(title==null?"Service":title,15,true));TextView d=tv(desc==null?"":desc,11,false);d.setTextColor(muted);x.addView(d);TextView go=tv("START NOW",12,true);go.setTextColor(purple);x.addView(go);return x;}
 View feature(String title,String desc,String icon,int color){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setGravity(Gravity.CENTER);x.setPadding(dp(4),dp(8),dp(4),dp(5));x.setBackground(stroke(Color.rgb(225,229,235),1,13));TextView i=tv(icon,24,true);i.setTextColor(color);i.setGravity(Gravity.CENTER);x.addView(i);TextView a=tv(title,12,true);a.setGravity(Gravity.CENTER);x.addView(a);TextView d=tv(desc,10,false);d.setTextColor(muted);d.setGravity(Gravity.CENTER);x.addView(d);return x;}
 View gigMini(String title,String pay,String icon){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(14),dp(10),dp(10),dp(8));x.setBackground(bg(white,14));TextView i=tv(icon,23,true);i.setTextColor(purple);x.addView(i);x.addView(tv(title==null?"Gig":title,15,true));TextView p=tv("Earn "+pay,13,true);p.setTextColor(purple);x.addView(p);x.addView(tv("View & Apply →",11,false));return x;}
 View bottomNav(){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);n.setPadding(dp(5),dp(3),dp(5),dp(3));n.setBackground(bg(white,20));String[] labels={"⌂\nHome","▤\nGigs","＋","🎯\nMy Leads","💰\nWithdraw"};for(int i=0;i<labels.length;i++){TextView b=tv(labels[i],i==2?25:11,true);b.setGravity(Gravity.CENTER);if(i==2){b.setTextColor(white);b.setBackground(bg(green,50));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(62),dp(62));p.setMargins(dp(5),-dp(14),dp(5),0);n.addView(b,p);b.setOnClickListener(v->leadQuickMenu());}else{b.setTextColor(i==0?purple:dark);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(62),1);n.addView(b,p);if(i==1)b.setOnClickListener(v->gigsScreen());if(i==3)b.setOnClickListener(v->leadsScreen());if(i==4)b.setOnClickListener(v->withdrawScreen());}}return n;}

 void workCategoriesScreen(){
  LinearLayout r=base();topBar(r,"Work & Earn — Categories");ScrollView s=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(dp(12),dp(8),dp(12),dp(20));s.addView(list);r.addView(s);
  db.collection("categories").whereEqualTo("status","active").get().addOnSuccessListener(q->{if(q.isEmpty()){for(String n:new String[]{"Customer Onboarding","Business Onboarding","Tele Marketing"}){TextView b=button(n+"  →",green);add(list,b,62,10);b.setOnClickListener(v->categoryItemsScreen(n));}}else for(DocumentSnapshot d:q){String n=d.getString("name");if(n==null)n="Other";TextView b=button((d.getString("icon")==null?"▣":d.getString("icon"))+"  "+n+"  →",green);add(list,b,62,10);String category=n;b.setOnClickListener(v->categoryItemsScreen(category));}}).addOnFailureListener(e->toast(err(e)));setContentView(r);
 }
 void categoryItemsScreen(String category){
  LinearLayout r=base();topBar(r,category);ScrollView s=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(dp(10),dp(8),dp(10),dp(20));s.addView(list);r.addView(s);
  TextView hint=tv("Choose a task or project, read its guidelines, then invite customers or share your link.",14,false);add(list,hint,75,4);
  db.collection("gigs").whereEqualTo("status","active").whereEqualTo("category",category).get().addOnSuccessListener(q->{if(q.isEmpty())list.addView(tv("No tasks in this category yet. Ask Admin to add tasks under this category.",14,false));for(DocumentSnapshot d:q){View card=gigCard(d);list.addView(card);card.setOnClickListener(v->guidelinesScreen(d));}}).addOnFailureListener(e->toast(err(e)));
  db.collection("projects").whereEqualTo("category",category).get().addOnSuccessListener(q->{for(DocumentSnapshot d:q){TextView b=button("PROJECT: "+String.valueOf(d.getString("title"))+"  →",purple);add(list,b,58,8);b.setOnClickListener(v->guidelinesScreen(d));}});
  setContentView(r);
 }
 void guidelinesScreen(DocumentSnapshot d){
  LinearLayout r=base();topBar(r,"Task & Project Guidelines");ScrollView s=new ScrollView(this);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(12),dp(16),dp(24));s.addView(c);r.addView(s);
  String title=String.valueOf(d.get("title")==null?"Task / Project":d.get("title"));String desc=String.valueOf(d.get("description")==null?"Follow the task instructions and submit genuine customer information only.":d.get("description"));String amount=String.valueOf(d.get("pay")==null?"0":d.get("pay"));
  TextView h=tv(title,23,true);add(c,h,65,0);TextView details=tv("Earning: ₹"+amount+"\n\nGUIDELINES\n"+desc+"\n\n1. Read the full task description.\n2. Get customer consent before sharing details.\n3. Submit genuine and correct information only.\n4. Admin will review and verify the lead before any eligible earning is credited.\n5. Do not promise a payout before approval.",15,false);details.setPadding(dp(14),dp(14),dp(14),dp(14));details.setBackground(stroke(Color.rgb(225,229,235),1,14));c.addView(details);
  TextView share=button("INVITE & SHARE LINK",green);add(c,share,54,16);share.setOnClickListener(v->shareGigToChrome(d));
  TextView lead=button("SUBMIT CUSTOMER LEAD",purple);add(c,lead,54,10);lead.setOnClickListener(v->leadSubmitScreen(d));
  TextView training=button("VIEW SCHEDULED TRAINING",purple2);add(c,training,54,10);training.setOnClickListener(v->trainingScreen());setContentView(r);
 }
 void teamScreen(){
   String ownerId=auth.getCurrentUser().getUid();
   LinearLayout r=base();topBar(r,"My Team");
   ScrollView scroll=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(dp(14),dp(10),dp(14),dp(24));scroll.addView(list);r.addView(scroll);
   TextView intro=tv("Build your GigSathi team\nAdd member details and keep your team directory in one place.",15,false);intro.setPadding(dp(12),dp(12),dp(12),dp(12));intro.setBackground(stroke(Color.rgb(225,229,235),1,14));list.addView(intro);
   TextView addMember=button("+ ADD TEAM MEMBER",green);add(list,addMember,54,12);
   TextView share=button("INVITE & SHARE GIGSATHI",purple);add(list,share,50,8);
   share.setOnClickListener(v->{String link="https://l86385138-pixel.github.io/app-creator-new/share.html?ref="+ownerId;Intent send=new Intent(Intent.ACTION_SEND);send.setType("text/plain");send.putExtra(Intent.EXTRA_TEXT,"Join my GigSathi team and explore work opportunities: "+link);startActivity(Intent.createChooser(send,"Invite team member"));});
   addMember.setOnClickListener(v->addTeamMemberForm(ownerId));
   TextView heading=tv("TEAM MEMBERS",18,true);heading.setPadding(0,dp(18),0,dp(8));list.addView(heading);
   db.collection("teamMembers").whereEqualTo("ownerId",ownerId).get().addOnSuccessListener(q->{if(q.isEmpty()){list.addView(tv("No team members added yet. Tap Add Team Member to add the first member.",14,false));return;}for(DocumentSnapshot d:q){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(10),dp(12),dp(10));card.setBackground(stroke(Color.rgb(225,229,235),1,12));card.addView(tv(String.valueOf(d.get("name")==null?"Team Member":d.get("name")),16,true));card.addView(tv("Mobile: "+String.valueOf(d.get("phone")==null?"—":d.get("phone")),13,false));card.addView(tv("Email: "+String.valueOf(d.get("email")==null||String.valueOf(d.get("email")).isEmpty()?"—":d.get("email")),13,false));card.addView(tv("Role: "+String.valueOf(d.get("memberRole")==null?"Member":d.get("memberRole"))+"  •  "+String.valueOf(d.get("status")==null?"Added":d.get("status")),12,true));TextView del=button("REMOVE MEMBER",purple);add(card,del,42,8);del.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Remove team member?").setMessage("This removes the member from your GigSathi team list.").setNegativeButton("Cancel",null).setPositiveButton("Remove",(dialog,which)->db.collection("teamMembers").document(d.getId()).delete().addOnSuccessListener(z->{toast("Team member removed.");teamScreen();}).addOnFailureListener(e->toast(err(e)))).show());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(6));list.addView(card,p);}}).addOnFailureListener(e->toast("Unable to load team: "+err(e)));
   setContentView(r);
  }
  boolean emValid(String em){return em!=null&&em.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$");}
  void addTeamMemberForm(String ownerId){
   LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(6),dp(4),dp(6),dp(4));
   EditText name=field("Member full name"),phone=field("Mobile number"),email=field("Member email (required for login)"),role=field("Role (e.g. Member / Team Leader)");
   for(EditText e:new EditText[]{name,phone,email,role})add(box,e,52,7);
   new AlertDialog.Builder(this).setTitle("Add Team Member").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Save Member",(dialog,which)->{
    String n=name.getText().toString().trim(),ph=phone.getText().toString().trim(),em=email.getText().toString().trim().toLowerCase(Locale.ROOT),rl=role.getText().toString().trim();
    if(n.length()<2||ph.replaceAll("\\D","").length()<10||!emValid(em)){toast("Enter member name, valid mobile and member email.");return;}
    Map<String,Object> data=new HashMap<>();data.put("ownerId",ownerId);data.put("name",n);data.put("phone",ph);data.put("email",em);data.put("memberRole",rl.isEmpty()?"Member":rl);data.put("status","invited");data.put("createdAt",FieldValue.serverTimestamp());
    db.collection("teamMembers").add(data).addOnSuccessListener(x->{toast("Team member added.");teamScreen();}).addOnFailureListener(e->toast("Could not add member: "+err(e)));
   }).show();
  }

  void trainingScreen(){
  LinearLayout r=base();topBar(r,"Scheduled Training");ScrollView s=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(dp(14),dp(10),dp(14),dp(20));s.addView(list);r.addView(s);
  db.collection("trainings").whereEqualTo("status","active").get().addOnSuccessListener(q->{if(q.isEmpty()){list.addView(tv("No scheduled training yet. Please check again later.",16,false));return;}for(DocumentSnapshot d:q){String title=d.getString("title")==null?"Training":d.getString("title");String schedule=d.getString("schedule")==null?"Schedule to be announced":d.getString("schedule");String link=d.getString("joinUrl")==null?"":d.getString("joinUrl");LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(10),dp(14),dp(10));card.setBackground(stroke(Color.rgb(225,229,235),1,12));card.addView(tv(title,17,true));card.addView(tv("Schedule: "+schedule,14,false));card.addView(tv(d.getString("description")==null?"":d.getString("description"),13,false));TextView join=button("JOIN TRAINING",green);add(card,join,48,8);join.setOnClickListener(v->{if(link.isEmpty()){toast("Admin has not added the training link yet.");return;}try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(link)));}catch(Exception e){toast("Unable to open training link.");}});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(180));p.setMargins(0,dp(8),0,dp(8));list.addView(card,p);}}).addOnFailureListener(e->toast(err(e)));setContentView(r);
 }
 void gigsScreen(){LinearLayout r=base();topBar(r,"Find Gigs & Services");LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);ScrollView s=new ScrollView(this);s.addView(list);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));db.collection("gigs").whereEqualTo("status","active").get().addOnSuccessListener(q->{if(q.isEmpty())list.addView(tv("No active gigs right now.",17,false));for(DocumentSnapshot d:q)list.addView(gigCard(d));});setContentView(r);}
 void gigDetail(DocumentSnapshot d){
 LinearLayout r=base(); topBar(r,"Product Detail");
 ScrollView s=new ScrollView(this); LinearLayout c=new LinearLayout(this); c.setOrientation(LinearLayout.VERTICAL); c.setPadding(dp(16),dp(8),dp(16),dp(90));
 TextView hero=tv("GIGSATHI\n"+String.valueOf(d.get("title")==null?"Project":d.get("title")),24,true); hero.setTextColor(white); hero.setPadding(dp(20),dp(22),dp(20),dp(18)); hero.setBackground(bg(purple,20)); c.addView(hero,new LinearLayout.LayoutParams(-1,dp(155)));
 LinearLayout stats=new LinearLayout(this); stats.setPadding(dp(0),dp(12),dp(0),dp(4)); stats.addView(stat("₹"+String.valueOf(d.get("pay")==null?"0":d.get("pay")),"TOTAL EARNING",purple),new LinearLayout.LayoutParams(0,dp(82),1)); stats.addView(stat(String.valueOf(d.get("leadCount")==null?"0":d.get("leadCount")),"TOTAL LEADS",purple),new LinearLayout.LayoutParams(0,dp(82),1)); stats.addView(stat(String.valueOf(d.get("sales")==null?"0":d.get("sales")),"TOTAL SALES",green),new LinearLayout.LayoutParams(0,dp(82),1)); c.addView(stats);
 LinearLayout tabs=new LinearLayout(this); String[] ts={"Details","Marketing","Training"}; for(String z:ts){TextView t=tv(z,17,true);t.setGravity(Gravity.CENTER);tabs.addView(t,new LinearLayout.LayoutParams(0,54,1));} c.addView(tabs);
 TextView details=tv("Offers\n\n"+String.valueOf(d.get("description")==null?"No details added yet.":d.get("description"))+"\n\nWhom to refer?\nEligible customers and referral information can be configured by Admin.\n\nTraining\nTraining information can be configured by Admin.",15,false); details.setPadding(dp(16),dp(16),dp(16),dp(16));details.setBackground(stroke(Color.rgb(225,229,235),1,14));c.addView(details);
 TextView apply=button("APPLY / SHARE TO CUSTOMER",purple2);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(54));ap.topMargin=dp(16);c.addView(apply,ap);apply.setOnClickListener(v->shareGigToChrome(d));
 TextView lead=button("SUBMIT CUSTOMER LEAD",purple);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(54));lp.topMargin=dp(10);c.addView(lead,lp);lead.setOnClickListener(v->leadSubmitScreen(d));
 TextView open=button("OPEN PRODUCT PAGE",green);LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(-1,dp(50));op.topMargin=dp(10);c.addView(open,op);open.setOnClickListener(v->openPublicPage(d));
 s.addView(c);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);
}
void shareGigToChrome(DocumentSnapshot d){
 String base="https://l86385138-pixel.github.io/app-creator-new/share.html";String title=String.valueOf(d.get("title")==null?"GigSathi Project":d.get("title"));String pay=String.valueOf(d.get("pay")==null?"0":d.get("pay"));String desc=String.valueOf(d.get("description")==null?"":d.get("description"));String url=String.valueOf(d.get("applyUrl")==null?"":d.get("applyUrl"));String image=String.valueOf(d.get("logoUrl")==null?"":d.get("logoUrl"));String leads=String.valueOf(d.get("leadCount")==null?"0":d.get("leadCount"));String sales=String.valueOf(d.get("sales")==null?"0":d.get("sales"));String workerId=auth.getCurrentUser().getUid();String workerName=auth.getCurrentUser().getDisplayName()==null?"Adviser":auth.getCurrentUser().getDisplayName();String gigId=d.getId();
 try{String link=base+"?title="+URLEncoder.encode(title,"UTF-8")+"&pay="+URLEncoder.encode(pay,"UTF-8")+"&desc="+URLEncoder.encode(desc,"UTF-8")+"&applyUrl="+URLEncoder.encode(url,"UTF-8")+"&image="+URLEncoder.encode(image,"UTF-8")+"&leads="+URLEncoder.encode(leads,"UTF-8")+"&sales="+URLEncoder.encode(sales,"UTF-8")+"&workerId="+URLEncoder.encode(workerId,"UTF-8")+"&workerName="+URLEncoder.encode(workerName,"UTF-8")+"&gigId="+URLEncoder.encode(gigId,"UTF-8");Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse(link));i.setPackage("com.android.chrome");try{startActivity(i);}catch(Exception ex){i.setPackage(null);startActivity(i);}}catch(Exception e){toast("Unable to open customer page.");}
}
void openPublicPage(DocumentSnapshot d){shareGigToChrome(d);}
View gigCard(DocumentSnapshot d){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(12),dp(16),dp(12));c.setBackground(bg(white,15));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(175));p.setMargins(dp(10),dp(7),dp(10),dp(7));c.setLayoutParams(p);c.addView(tv(String.valueOf(d.get("title")),18,true));c.addView(tv("Earn ₹"+String.valueOf(d.get("pay")==null?"":d.get("pay"))+"  •  "+String.valueOf(d.get("location")==null?"Any":d.get("location")),13,false));c.addView(tv(String.valueOf(d.get("description")==null?"":d.get("description")),12,false),new LinearLayout.LayoutParams(-1,dp(55)));TextView a=button("APPLY NOW",purple);c.addView(a,new LinearLayout.LayoutParams(-1,dp(44)));a.setOnClickListener(v->gigDetail(d));return c;}
 void apply(DocumentSnapshot d){Map<String,Object>m=new HashMap<>();m.put("workerId",auth.getCurrentUser().getUid());m.put("workerEmail",auth.getCurrentUser().getEmail());m.put("gigId",d.getId());m.put("gigTitle",d.getString("title"));m.put("status","pending");m.put("createdAt",FieldValue.serverTimestamp());db.collection("applications").add(m).addOnSuccessListener(x->toast("Application submitted successfully.")).addOnFailureListener(e->toast(err(e)));}
 void leadQuickMenu(){new AlertDialog.Builder(this).setTitle("GigSathi Lead").setItems(new String[]{"My Leads","Submit Lead","Withdraw Earnings"},(d,w)->{if(w==0)leadsScreen();else if(w==1)leadSubmitScreen(null);else withdrawScreen();}).show();}
 void leadSubmitScreen(DocumentSnapshot gig){
  LinearLayout r=base();topBar(r,"Submit Customer Lead");ScrollView s=new ScrollView(this);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(8),dp(16),dp(30));
  TextView info=tv("Submit genuine customer information. Admin will review the lead.",15,true);info.setTextColor(muted);c.addView(info);
  EditText name=field("Customer full name"),phone=field("Customer mobile"),pin=field("Pincode"),title=field("Gig / Product title"),amount=field("Task amount");
  if(gig!=null){title.setText(String.valueOf(gig.get("title")==null?"":gig.get("title")));amount.setText(String.valueOf(gig.get("pay")==null?"0":gig.get("pay")));title.setEnabled(false);amount.setEnabled(false);}
  for(EditText x:new EditText[]{name,phone,pin,title,amount})add(c,x,54,9);
  TextView save=button("SUBMIT LEAD",purple);add(c,save,54,18);save.setOnClickListener(v->{String a=amount.getText().toString().trim();if(name.getText().toString().trim().isEmpty()||phone.getText().toString().trim().isEmpty()||pin.getText().toString().trim().isEmpty()||title.getText().toString().trim().isEmpty()||a.isEmpty()){toast("Please fill all lead fields.");return;}double amt;try{amt=Double.parseDouble(a);}catch(Exception e){toast("Invalid task amount.");return;}String uid=auth.getCurrentUser().getUid();db.collection("users").document(uid).get().addOnSuccessListener(profile->{String role=profile.getString("role");String owner="member".equals(role)?profile.getString("ownerId"):uid;if(owner==null||owner.isEmpty()){toast("Team Owner account is missing. Contact support.");return;}Map<String,Object>m=new HashMap<>();m.put("workerId",owner);m.put("workerEmail",profile.getString("email"));if("member".equals(role))m.put("memberId",uid);m.put("submittedBy",uid);m.put("customerName",name.getText().toString().trim());m.put("phone",phone.getText().toString().trim());m.put("pincode",pin.getText().toString().trim());m.put("gigTitle",title.getText().toString().trim());m.put("taskAmount",amt);m.put("status","interview_pending");m.put("walletCredited",false);m.put("createdAt",FieldValue.serverTimestamp());db.collection("leads").add(m).addOnSuccessListener(x->{toast("Lead submitted. Interview Pending.");if("member".equals(role))memberLeadsScreen();else leadsScreen();}).addOnFailureListener(e->toast(err(e)));}).addOnFailureListener(e->toast(err(e)));});s.addView(c);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);
 }
 void leadsScreen(){
  LinearLayout r=base();topBar(r,"My Leads");ScrollView s=new ScrollView(this);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(8),dp(14),dp(30));TextView add=button("＋ SUBMIT NEW LEAD",purple);add(c,add,52,8);add.setOnClickListener(v->leadSubmitScreen(null));
  db.collection("leads").whereEqualTo("workerId",auth.getCurrentUser().getUid()).get().addOnSuccessListener(q->{if(q.isEmpty())c.addView(tv("No leads submitted yet.",16,false));for(DocumentSnapshot d:q){String st=String.valueOf(d.get("status")==null?"interview_pending":d.get("status"));String label=st.equals("interview_pending")?"INTERVIEW PENDING":st.equals("verify")?"VERIFY":st.equals("complete")?"COMPLETE":st.equals("reject")?"REJECT":st.toUpperCase();String amt=String.valueOf(d.get("taskAmount")==null?"0":d.get("taskAmount"));LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(10),dp(14),dp(10));card.setBackground(stroke(Color.rgb(225,229,235),1,14));card.addView(tv(String.valueOf(d.get("customerName")==null?"Customer":d.get("customerName")),17,true));card.addView(tv(String.valueOf(d.get("gigTitle")==null?"":d.get("gigTitle")),13,false));TextView ss=tv("STATUS: "+label,13,true);ss.setTextColor(st.equals("reject")?Color.rgb(190,50,50):st.equals("complete")?green:purple);card.addView(ss);card.addView(tv("Task Amount: ₹"+amt,13,true));if(Boolean.TRUE.equals(d.getBoolean("walletCredited")))card.addView(tv("✓ Amount credited to wallet",12,true));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(132));cp.setMargins(0,dp(7),0,dp(7));c.addView(card,cp);}}).addOnFailureListener(e->toast(err(e)));s.addView(c);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);
 }
 void withdrawScreen(){
  final String uid=auth.getCurrentUser().getUid();
  db.collection("users").document(uid).get().addOnSuccessListener(u->{LinearLayout r=base();topBar(r,"Withdraw Earnings");ScrollView s=new ScrollView(this);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(10),dp(16),dp(30));double wallet=0;Object w=u.get("wallet");if(w instanceof Number)wallet=((Number)w).doubleValue();
  TextView bal=tv("AVAILABLE BALANCE\n₹"+wallet,24,true);bal.setTextColor(green);bal.setPadding(dp(16),dp(16),dp(16),dp(16));bal.setBackground(stroke(Color.rgb(215,222,228),1,14));c.addView(bal,new LinearLayout.LayoutParams(-1,dp(100)));
  EditText amt=field("Withdrawal amount"),upi=field("UPI ID / Payment details");add(c,amt,54,14);add(c,upi,54,8);TextView req=button("REQUEST WITHDRAWAL",purple);add(c,req,54,16);
  req.setOnClickListener(v->{double a;try{a=Double.parseDouble(amt.getText().toString().trim());}catch(Exception ex){toast("Enter valid amount.");return;}if(a<=0){toast("Enter a valid amount.");return;}if(upi.getText().toString().trim().isEmpty()){toast("Enter UPI/payment details.");return;}
   DocumentReference ur=db.collection("users").document(uid);DocumentReference wr=db.collection("withdrawals").document();
   db.runTransaction(t->{DocumentSnapshot us=t.get(ur);Object ow=us.get("wallet");double current=ow instanceof Number?((Number)ow).doubleValue():0;if(a>current)throw new FirebaseFirestoreException("Insufficient wallet balance.",FirebaseFirestoreException.Code.ABORTED);Map<String,Object>m2=new HashMap<>();m2.put("workerId",uid);m2.put("workerEmail",auth.getCurrentUser().getEmail());m2.put("amount",a);m2.put("upiId",upi.getText().toString().trim());m2.put("status","pending");m2.put("createdAt",FieldValue.serverTimestamp());m2.put("requestId",wr.getId());t.update(ur,"wallet",current-a,"updatedAt",FieldValue.serverTimestamp(),"lastWithdrawalRequestId",wr.getId());t.set(wr,m2);return null;}).addOnSuccessListener(x->{toast("Withdrawal request submitted.");withdrawScreen();}).addOnFailureListener(ex->toast(err(ex)));
  });
  TextView h=tv("WITHDRAWAL HISTORY",18,true);h.setPadding(0,dp(22),0,dp(8));c.addView(h);
  db.collection("withdrawals").whereEqualTo("workerId",uid).get().addOnSuccessListener(q->{for(DocumentSnapshot d:q){c.addView(tv("₹"+String.valueOf(d.get("amount")==null?"0":d.get("amount"))+"  •  "+String.valueOf(d.get("status")==null?"pending":d.get("status"))+"\n"+String.valueOf(d.get("upiId")==null?"":d.get("upiId")),14,false));}});
  s.addView(c);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);});
 }
 void profileScreen(){
   final String uid=auth.getCurrentUser().getUid();
   db.collection("users").document(uid).get().addOnSuccessListener(u->{
    LinearLayout root=base();root.setBackgroundColor(Color.rgb(250,250,250));ScrollView sc=new ScrollView(this);LinearLayout c=new LinearLayout(this);c.setOrientation(1);c.setPadding(dp(16),dp(8),dp(16),dp(28));
    LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);TextView back=tv("‹",34,true);back.setTextColor(Color.BLACK);bar.addView(back,new LinearLayout.LayoutParams(dp(48),dp(58)));back.setOnClickListener(v->home(u));TextView title=tv("My Profile",23,true);bar.addView(title,new LinearLayout.LayoutParams(0,dp(58),1));c.addView(bar);
    LinearLayout card=new LinearLayout(this);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(14),dp(14),dp(10),dp(14));card.setBackground(stroke(white,1,22));
    TextView avatar=tv(initialOf(u.getString("name")),30,true);avatar.setTextColor(white);avatar.setGravity(Gravity.CENTER);avatar.setBackground(bg(Color.rgb(65,130,239),100));card.addView(avatar,new LinearLayout.LayoutParams(dp(82),dp(82)));
    LinearLayout info=new LinearLayout(this);info.setOrientation(1);info.setPadding(dp(12),0,dp(4),0);String name=u.getString("name");if(name==null||name.trim().isEmpty())name="Adviser";TextView nm=tv(name.toUpperCase(Locale.ROOT),17,true);info.addView(nm);String email=auth.getCurrentUser().getEmail();if(email==null)email="";TextView em=tv(email,13,false);em.setTextColor(muted);info.addView(em);String phone=u.getString("phone");if(phone==null)phone="";info.addView(tv(phone,13,false));TextView role=tv("Adviser",12,true);role.setTextColor(Color.rgb(65,130,239));role.setBackground(bg(Color.rgb(234,240,255),10));role.setPadding(dp(9),dp(4),dp(9),dp(4));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-2,-2);rp.topMargin=dp(6);info.addView(role,rp);card.addView(info,new LinearLayout.LayoutParams(0,-2,1));TextView arrow=tv("›",30,false);arrow.setTextColor(muted);card.addView(arrow);card.setOnClickListener(v->editPersonal(u));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.topMargin=dp(8);cp.bottomMargin=dp(18);c.addView(card,cp);
    LinearLayout earning=new LinearLayout(this);earning.setGravity(Gravity.CENTER_VERTICAL);earning.setPadding(dp(16),dp(14),dp(12),dp(14));earning.setBackground(bg(Color.rgb(91,180,123),20));TextView rupee=tv("₹",24,true);rupee.setTextColor(white);rupee.setGravity(Gravity.CENTER);rupee.setBackground(bg(Color.rgb(120,198,145),14));earning.addView(rupee,new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout et=new LinearLayout(this);et.setOrientation(1);et.setPadding(dp(12),0,0,0);TextView earnTitle=tv("Earnings",17,true);earnTitle.setTextColor(white);et.addView(earnTitle);TextView earnSub=tv("Track payouts & incentives",13,true);earnSub.setTextColor(white);et.addView(earnSub);earning.addView(et,new LinearLayout.LayoutParams(0,-2,1));TextView ea=tv("›",30,true);ea.setTextColor(white);earning.addView(ea);earning.setOnClickListener(v->withdrawScreen());LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,-2);ep.bottomMargin=dp(16);c.addView(earning,ep);
    addProfileRow(c,"▣","KYC Details","Aadhaar/PAN and verification status",v->editKyc(u));
    LinearLayout two=new LinearLayout(this);two.setOrientation(0);View website=profileTile("◎","My Website");LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,dp(120),1);tp.setMargins(0,dp(10),dp(6),dp(10));two.addView(website,tp);website.setOnClickListener(v->openAdvisorWebsite(u));View team=profileTile("♟","My Team");LinearLayout.LayoutParams t2=new LinearLayout.LayoutParams(0,dp(120),1);t2.setMargins(dp(6),dp(10),0,dp(10));two.addView(team,t2);team.setOnClickListener(v->teamScreen());c.addView(two);
    LinearLayout group=new LinearLayout(this);group.setOrientation(1);group.setBackground(stroke(white,1,20));addProfileRow(group,"♧","My Referrals","View your referrals",v->showInfo("My Referrals","Your referral details will appear here."));addProfileRow(group,"♟","Become an Agency","Explore agency opportunities",v->showInfo("Become an Agency","Contact support to learn about agency onboarding."));addProfileRow(group,"♧","Customer Support","Get help with your account",v->helpSupport());LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,-2);gp.topMargin=dp(8);gp.bottomMargin=dp(18);c.addView(group,gp);
    TextView more=button("⌄   More Options",purple2);more.setBackground(stroke(white,1,18));add(c,more,64,0);more.setOnClickListener(v->{LinearLayout extra=new LinearLayout(this);extra.setOrientation(1);addProfileRow(extra,"♙","Personal Details","Name, phone, email, city, address",x->editPersonal(u));addProfileRow(extra,"₹","Payment Settings","UPI, bank account, account holder",x->editPayment(u));addProfileRow(extra,"▣","Professional Details","Skills, experience, profession",x->editProfessional(u));addProfileRow(extra,"🪪","Adviser ID Card","View and share your GigSathi adviser ID",x->workerIdCard(u));addProfileRow(extra,"📄","Offer Letter","View and share your adviser offer letter draft",x->workerOfferLetter(u));addProfileRow(extra,"🎓","Education Details","Qualification, institute, year",x->editEducation(u));addProfileRow(extra,"🏆","Contest History","View completed contests",x->contestHistory());addProfileRow(extra,"🔒","M-PIN","Set or change your secure app PIN",x->editPin());addProfileRow(extra,"GST","GST Management","GST number and business details",x->editGst(u));addProfileRow(extra,"📄","Adviser Agreement","GigSathi adviser terms",x->showInfo("Adviser Agreement","Please review the adviser agreement before accepting work."));addProfileRow(extra,"🔐","Privacy Policy","How your account information is used",x->showInfo("Privacy Policy","Your account information is used to operate GigSathi services, applications, payments and support."));addProfileRow(extra,"↪","Sign Out","Sign out of this account",x->{auth.signOut();login();});int idx=c.indexOfChild(more);c.addView(extra,idx+1);more.setEnabled(false);});
    TextView del=button("DELETE ACCOUNT",Color.rgb(205,55,70));add(c,del,50,20);del.setOnClickListener(v->deleteAccountConfirm(u));TextView ver=tv("App Version\n3.1.8.82",12,false);ver.setTextColor(muted);ver.setGravity(Gravity.CENTER);add(c,ver,-2,26);
    sc.addView(c);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
   }).addOnFailureListener(e->toast(err(e)));
  }
 String initialOf(String name){return name==null||name.trim().isEmpty()?"A":name.trim().substring(0,1).toUpperCase(Locale.ROOT);}
 View profileTile(String icon,String label){LinearLayout x=new LinearLayout(this);x.setOrientation(1);x.setGravity(Gravity.CENTER);x.setBackground(stroke(white,1,20));x.setElevation(dp(1));TextView i=tv(icon,25,true);i.setTextColor(Color.rgb(30,126,225));i.setGravity(Gravity.CENTER);i.setBackground(bg(Color.rgb(234,242,255),12));x.addView(i,new LinearLayout.LayoutParams(dp(48),dp(48)));TextView t=tv(label,15,true);t.setGravity(Gravity.CENTER);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(10);x.addView(t,p);return x;}
 void openAdvisorWebsite(DocumentSnapshot u){String advisorUid=null;for(String key:new String[]{"advisorUid","referralCode","referralId","uid"}){String v=u.getString(key);if(v!=null&&!v.trim().isEmpty()){advisorUid=v.trim();break;}}if(advisorUid==null)advisorUid=auth.getCurrentUser().getUid();String url="https://adwizor.in/finAdvisor/?uid="+Uri.encode(advisorUid);Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse(url));try{startActivity(i);}catch(Exception e){toast("Could not open adviser website");}}
 void addProfileRow(LinearLayout c,String icon,String title,String sub,View.OnClickListener l){
  LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(4),dp(6),dp(4),dp(6));row.setClickable(true);
  TextView i=tv(icon,24,true);i.setGravity(Gravity.CENTER);i.setTextColor(purple);row.addView(i,new LinearLayout.LayoutParams(dp(58),dp(68)));
  LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(tv(title,17,true));TextView s=tv(sub,11,false);s.setTextColor(muted);tx.addView(s);row.addView(tx,new LinearLayout.LayoutParams(0,dp(68),1));
  TextView a=tv("›",30,false);a.setTextColor(purple2);a.setGravity(Gravity.CENTER);row.addView(a,new LinearLayout.LayoutParams(dp(45),dp(68)));row.setOnClickListener(l);c.addView(row,new LinearLayout.LayoutParams(-1,dp(78)));
 }
 EditText dialogField(LinearLayout box,String label,String value){TextView l=tv(label,12,true);l.setTextColor(muted);box.addView(l);EditText e=field(label);if(value!=null)e.setText(value);box.addView(e,new LinearLayout.LayoutParams(-1,dp(50)));return e;}
 void saveFields(String msg,Map<String,Object> m){db.collection("users").document(auth.getCurrentUser().getUid()).update(m).addOnSuccessListener(v->toast(msg)).addOnFailureListener(e->toast(err(e)));}
 void editPersonal(DocumentSnapshot u){
  LinearLayout b=base();b.setPadding(dp(8),0,dp(8),0);EditText n=dialogField(b,"Full Name",u.getString("name"));EditText ph=dialogField(b,"Mobile",u.getString("phone"));EditText em=dialogField(b,"Email",u.getString("email"));EditText city=dialogField(b,"City",u.getString("location"));EditText addr=dialogField(b,"Address",u.getString("address"));
  new AlertDialog.Builder(this).setTitle("Personal Details").setView(b).setPositiveButton("SAVE",(d,w)->{Map<String,Object>m=new HashMap<>();m.put("name",n.getText().toString().trim());m.put("phone",ph.getText().toString().trim());m.put("email",em.getText().toString().trim());m.put("location",city.getText().toString().trim());m.put("address",addr.getText().toString().trim());saveFields("Personal details updated.",m);}).setNegativeButton("CANCEL",null).show();
 }
 void editPayment(DocumentSnapshot u){
  LinearLayout b=base();b.setPadding(dp(8),0,dp(8),0);EditText upi=dialogField(b,"UPI ID",u.getString("upiId"));EditText holder=dialogField(b,"Account Holder",u.getString("accountHolder"));EditText bank=dialogField(b,"Bank Name",u.getString("bankName"));EditText acc=dialogField(b,"Account Number",u.getString("accountNumber"));EditText ifsc=dialogField(b,"IFSC",u.getString("ifsc"));
  new AlertDialog.Builder(this).setTitle("Payment Settings").setView(b).setPositiveButton("SAVE",(d,w)->{Map<String,Object>m=new HashMap<>();m.put("upiId",upi.getText().toString().trim());m.put("accountHolder",holder.getText().toString().trim());m.put("bankName",bank.getText().toString().trim());m.put("accountNumber",acc.getText().toString().trim());m.put("ifsc",ifsc.getText().toString().trim());saveFields("Payment settings updated.",m);}).setNegativeButton("CANCEL",null).show();
 }
 void editProfessional(DocumentSnapshot u){
  LinearLayout b=base();b.setPadding(dp(8),0,dp(8),0);EditText skill=dialogField(b,"Skills",u.getString("skills"));EditText prof=dialogField(b,"Profession",u.getString("profession"));EditText exp=dialogField(b,"Experience",u.getString("experience"));EditText bio=dialogField(b,"About / Bio",u.getString("bio"));
  new AlertDialog.Builder(this).setTitle("Professional Details").setView(b).setPositiveButton("SAVE",(d,w)->{Map<String,Object>m=new HashMap<>();m.put("skills",skill.getText().toString().trim());m.put("profession",prof.getText().toString().trim());m.put("experience",exp.getText().toString().trim());m.put("bio",bio.getText().toString().trim());saveFields("Professional details updated.",m);}).setNegativeButton("CANCEL",null).show();
 }
 void editKyc(DocumentSnapshot u){
  LinearLayout b=base();b.setPadding(dp(8),0,dp(8),0);EditText pan=dialogField(b,"PAN Number",u.getString("pan"));EditText aad=dialogField(b,"Aadhaar Last 4 Digits",u.getString("aadhaarLast4"));EditText status=dialogField(b,"KYC Status",u.getString("kycStatus"));status.setEnabled(false);
  new AlertDialog.Builder(this).setTitle("KYC Details").setView(b).setPositiveButton("SAVE",(d,w)->{Map<String,Object>m=new HashMap<>();m.put("pan",pan.getText().toString().trim());m.put("aadhaarLast4",aad.getText().toString().trim());m.put("kycStatus",u.getString("kycStatus")==null?"pending":u.getString("kycStatus"));saveFields("KYC details updated.",m);}).setNegativeButton("CANCEL",null).show();
 }
 void editEducation(DocumentSnapshot u){
  LinearLayout b=base();b.setPadding(dp(8),0,dp(8),0);EditText q=dialogField(b,"Qualification",u.getString("qualification"));EditText inst=dialogField(b,"Institute",u.getString("institute"));EditText year=dialogField(b,"Passing Year",u.getString("passingYear"));
  new AlertDialog.Builder(this).setTitle("Education Details").setView(b).setPositiveButton("SAVE",(d,w)->{Map<String,Object>m=new HashMap<>();m.put("qualification",q.getText().toString().trim());m.put("institute",inst.getText().toString().trim());m.put("passingYear",year.getText().toString().trim());saveFields("Education details updated.",m);}).setNegativeButton("CANCEL",null).show();
 }
 void editGst(DocumentSnapshot u){
  LinearLayout b=base();b.setPadding(dp(8),0,dp(8),0);EditText gst=dialogField(b,"GST Number",u.getString("gstNumber"));EditText business=dialogField(b,"Business Name",u.getString("businessName"));EditText address=dialogField(b,"Business Address",u.getString("businessAddress"));
  new AlertDialog.Builder(this).setTitle("GST Management").setView(b).setPositiveButton("SAVE",(d,w)->{Map<String,Object>m=new HashMap<>();m.put("gstNumber",gst.getText().toString().trim());m.put("businessName",business.getText().toString().trim());m.put("businessAddress",address.getText().toString().trim());saveFields("GST details updated.",m);}).setNegativeButton("CANCEL",null).show();
 }
 void editPin(){
  final String uid=auth.getCurrentUser().getUid();android.content.SharedPreferences p=getSharedPreferences("gigbiz_secure",MODE_PRIVATE);String old=p.getString("mpin","");
  LinearLayout b=base();b.setPadding(dp(8),0,dp(8),0);EditText pin=dialogField(b,old.isEmpty()?"Create 4 digit M-PIN":"New 4 digit M-PIN","");pin.setInputType(2);new AlertDialog.Builder(this).setTitle(old.isEmpty()?"Set M-PIN":"Change M-PIN").setView(b).setPositiveButton("SAVE",(d,w)->{String x=pin.getText().toString().trim();if(x.length()!=4){toast("M-PIN must be exactly 4 digits.");return;}p.edit().putString("mpin",x).apply();toast("M-PIN saved on this device.");}).setNegativeButton("CANCEL",null).show();
 }
 void contestHistory(){
  LinearLayout b=base();b.setPadding(dp(8),0,dp(8),0);ScrollView s=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);s.addView(list);b.addView(s,new LinearLayout.LayoutParams(-1,dp(320)));
  db.collection("contestHistory").whereEqualTo("workerId",auth.getCurrentUser().getUid()).get().addOnSuccessListener(q->{if(q.isEmpty())list.addView(tv("No contest history yet.",15,false));for(DocumentSnapshot d:q)list.addView(tv("🏆 "+String.valueOf(d.get("title"))+"\nStatus: "+String.valueOf(d.get("status"))+"\nReward: ₹"+String.valueOf(d.get("reward")==null?"0":d.get("reward")),14,false));});
  new AlertDialog.Builder(this).setTitle("Contest History").setView(b).setPositiveButton("CLOSE",null).show();
 }
 void helpSupport(){
  new AlertDialog.Builder(this).setTitle("Help & Support").setMessage("Need help with your GigSathi account, work, payment or KYC?\n\nUse your registered email to contact support.").setPositiveButton("EMAIL SUPPORT",(d,w)->{Intent i=new Intent(Intent.ACTION_SENDTO,Uri.parse("mailto:"));i.putExtra(Intent.EXTRA_SUBJECT,"GigSathi Adviser Support");try{startActivity(i);}catch(Exception e){toast("No email app found.");}}).setNegativeButton("CLOSE",null).show();
 }
 void shareProfile(DocumentSnapshot u){
  String n=u.getString("name");if(n==null)n="GigSathi Adviser";String text=n+"\nSkills: "+String.valueOf(u.get("skills")==null?"":u.get("skills"))+"\nLocation: "+String.valueOf(u.get("location")==null?"":u.get("location"))+"\nContact: "+String.valueOf(u.get("phone")==null?"":u.get("phone"));
  Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,text);startActivity(Intent.createChooser(i,"Share Your Card"));
 }
 void workerIdCard(DocumentSnapshot u){
  String uid=auth.getCurrentUser().getUid();
  String adviserId=uid.substring(0,Math.min(8,uid.length())).toUpperCase(Locale.ROOT);
  String name=u.getString("name");if(name==null||name.trim().isEmpty())name="Adviser";
  String phone=u.getString("phone");if(phone==null||phone.trim().isEmpty())phone="Not provided";
  String email=auth.getCurrentUser().getEmail();if(email==null)email="";
  String skills=u.getString("skills");if(skills==null||skills.trim().isEmpty())skills="Not provided";
  String status=String.valueOf(u.get("status")==null?"Active":u.get("status"));
  LinearLayout root=base();topBar(root,"Adviser ID Card");
  ScrollView sc=new ScrollView(this);LinearLayout content=new LinearLayout(this);content.setOrientation(1);content.setPadding(dp(16),dp(14),dp(16),dp(24));sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
  int navy=Color.rgb(8,42,91),orange=Color.rgb(245,126,32),pale=Color.rgb(242,247,253);
  LinearLayout card=new LinearLayout(this);card.setOrientation(1);card.setPadding(dp(18),dp(18),dp(18),dp(18));card.setBackground(bg(navy,20));
  TextView brand=tv("GigSathi",25,true);brand.setTextColor(white);card.addView(brand);
  TextView strap=tv("TOGETHER FOR A BETTER TOMORROW",10,true);strap.setTextColor(Color.rgb(255,174,75));card.addView(strap);
  workerPhotoView=new ImageView(this);workerPhotoView.setScaleType(ImageView.ScaleType.CENTER_CROP);workerPhotoView.setBackground(bg(white,60));workerPhotoView.setClipToOutline(true);LinearLayout.LayoutParams photoParams=new LinearLayout.LayoutParams(dp(94),dp(94));photoParams.gravity=Gravity.CENTER;photoParams.topMargin=dp(12);card.addView(workerPhotoView,photoParams);
  String photo=getSharedPreferences("gigbiz_worker_photos",MODE_PRIVATE).getString(uid,"");if(!photo.isEmpty()){try{workerPhotoView.setImageURI(Uri.parse(photo));}catch(Exception ignored){workerPhotoView.setImageResource(com.gigbiz.app.R.drawable.ic_gigbiz);}}else workerPhotoView.setImageResource(com.gigbiz.app.R.drawable.ic_gigbiz);
  TextView photoBtn=button("UPLOAD ADVISER PHOTO",orange);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(42));pp.topMargin=dp(10);card.addView(photoBtn,pp);photoBtn.setOnClickListener(v->{Intent pick=new Intent(Intent.ACTION_OPEN_DOCUMENT);pick.addCategory(Intent.CATEGORY_OPENABLE);pick.setType("image/*");startActivityForResult(pick,PICK_WORKER_PHOTO);});
  TextView nm=tv(name,22,true);nm.setTextColor(white);nm.setGravity(Gravity.CENTER);LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-1,-2);np.topMargin=dp(8);card.addView(nm,np);
  TextView role=tv("ADVISER",13,true);role.setTextColor(Color.rgb(255,174,75));role.setGravity(Gravity.CENTER);card.addView(role);
  View line=new View(this);line.setBackgroundColor(Color.rgb(245,126,32));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(2));lp.setMargins(0,dp(12),0,dp(8));card.addView(line,lp);
  TextView details=tv("ADVISER ID   "+adviserId+"\n\nMOBILE   "+phone+"\nEMAIL   "+email+"\nSKILLS   "+skills+"\nSTATUS   "+status,13,false);details.setTextColor(white);details.setPadding(dp(4),dp(8),dp(4),dp(8));card.addView(details);
  TextView foot=tv("DIGITAL PROFILE ID • NOT A GOVERNMENT ID",9,true);foot.setTextColor(Color.rgb(255,174,75));foot.setGravity(Gravity.CENTER);card.addView(foot);
  content.addView(card,new LinearLayout.LayoutParams(-1,-2));
  TextView note=tv("Your ID details are taken from your GigSathi profile. Keep them up to date.",12,false);note.setTextColor(muted);add(content,note,-2,12);
  final String shareName=name,sharePhone=phone,shareEmail=email,shareSkills=skills,shareStatus=status,shareId=adviserId;
  idPdfText="GIGSATHI ADVISER ID CARD\nName: "+shareName+"\nRole: Adviser\nAdviser ID: "+shareId+"\nMobile: "+sharePhone+"\nEmail: "+shareEmail+"\nSkills: "+shareSkills+"\nStatus: "+shareStatus+"\n\nDigital profile ID only; not a government identity document.";
  TextView pdf=button("DOWNLOAD ADVISER ID CARD PDF",navy);add(content,pdf,52,14);pdf.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/pdf");i.putExtra(Intent.EXTRA_TITLE,"GigSathi_Adviser_ID_Card.pdf");startActivityForResult(i,715);});
  TextView share=button("SHARE ADVISER ID",orange);add(content,share,50,9);share.setOnClickListener(v->shareDocument("GigSathi Adviser ID Card",idPdfText));
  setContentView(root);
 }
 @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){
  super.onActivityResult(requestCode,resultCode,data);if(resultCode!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();
  if(requestCode==PICK_WORKER_PHOTO){String uid=auth.getCurrentUser()==null?"":auth.getCurrentUser().getUid();if(uid.isEmpty())return;try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}getSharedPreferences("gigbiz_worker_photos",MODE_PRIVATE).edit().putString(uid,uri.toString()).apply();if(workerPhotoView!=null)workerPhotoView.setImageURI(uri);storage.getReference().child("worker-photos/"+uid+"/id-photo.jpg").putFile(uri).addOnSuccessListener(t->t.getStorage().getDownloadUrl().addOnSuccessListener(url->db.collection("users").document(uid).update("workerPhotoUrl",url.toString()).addOnSuccessListener(v->toast("Adviser photo uploaded.")).addOnFailureListener(e->toast("Photo saved, profile update failed: "+err(e))))).addOnFailureListener(e->toast("Photo selected on device, cloud upload failed: "+err(e)));return;}
  if(requestCode==714||requestCode==715){boolean idCard=requestCode==715;String content=idCard?idPdfText:offerPdfText;try{
   PdfDocument pdf=new PdfDocument();Paint p=new Paint(3);int pageW=idCard?420:595,pageH=idCard?660:842;
   PdfDocument.Page page=pdf.startPage(new PdfDocument.PageInfo.Builder(pageW,pageH,1).create());Canvas canvas=page.getCanvas();
   int navy=Color.rgb(8,42,91),orange=Color.rgb(245,126,32);canvas.drawColor(Color.WHITE);p.setColor(navy);canvas.drawRect(0,0,pageW,idCard?115:105,p);
   p.setColor(orange);canvas.drawRect(0,idCard?110:100,pageW,idCard?116:106,p);
   p.setColor(Color.WHITE);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(idCard?26:23);canvas.drawText("GigSathi",32,42,p);
   p.setTypeface(Typeface.DEFAULT);p.setTextSize(9);canvas.drawText("TOGETHER FOR A BETTER TOMORROW",32,63,p);
   p.setColor(navy);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(idCard?15:18);canvas.drawText(idCard?"ADVISER ID CARD":"ADVISER OFFER LETTER — DRAFT",32,idCard?145:137,p);
   p.setColor(Color.DKGRAY);p.setTypeface(Typeface.DEFAULT);p.setTextSize(idCard?11:10);int y=idCard?177:166;int left=32,maxChars=idCard?43:83,lineHeight=idCard?25:17;
   for(String paragraph:content.split("\\n")){String remaining=paragraph;if(remaining.isEmpty()){y+=lineHeight/2;continue;}while(remaining.length()>maxChars){int cut=remaining.lastIndexOf(' ',maxChars);if(cut<1)cut=maxChars;canvas.drawText(remaining.substring(0,cut),left,y,p);remaining=remaining.substring(cut).trim();y+=lineHeight;if(y>pageH-55)break;}if(y<=pageH-55){canvas.drawText(remaining,left,y,p);y+=lineHeight;}if(y>pageH-55)break;}
   p.setColor(orange);canvas.drawRect(0,pageH-42,pageW, pageH,p);p.setColor(Color.WHITE);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(9);canvas.drawText(idCard?"DIGITAL PROFILE ID • NOT A GOVERNMENT ID":"DRAFT ONLY • REVIEW AND AUTHORIZE BEFORE ISSUE",32,pageH-17,p);
   pdf.finishPage(page);OutputStream out=getContentResolver().openOutputStream(uri);if(out==null)throw new java.io.IOException("Cannot save PDF");pdf.writeTo(out);out.close();pdf.close();toast(idCard?"Adviser ID Card PDF saved.":"Offer Letter PDF saved.");
  }catch(Exception e){toast("PDF error: "+e.getMessage());}}
 }
 String idPdfText="";
 String offerPdfText="";
 void workerOfferLetter(DocumentSnapshot u){
  String name=u.getString("name");if(name==null||name.trim().isEmpty())name="Adviser";
  String email=auth.getCurrentUser().getEmail();if(email==null)email="";
  String phone=u.getString("phone");if(phone==null)phone="Not provided";
  String date=java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM,java.util.Locale.getDefault()).format(new java.util.Date());
  String letter="GREAT INDIA TECHNOLOGY™ / GIGSATHI\nADVISER OFFER LETTER — DRAFT\nDate: "+date+"\n\nTo: "+name+"\nEmail: "+email+"\nMobile: "+phone+"\n\nDear "+name+",\n\nWe invite you to register your interest in performing eligible tasks and projects through the GigSathi platform. Work availability, task instructions, eligibility, verification and any payment are subject to the applicable task terms and review by the platform administrator.\n\nRole: Independent platform adviser / task participant\nWork type: Task- or project-based, as offered in the app\nPayment: Only the amount shown for a task that is completed and approved under its stated terms\n\nThis document is a draft template for review. It is not proof of employment, a guarantee of work, or a guarantee of income. It becomes an official offer only if separately reviewed and signed by an authorized representative with the final terms.\n\nRegards,\nLavkush R\nGreat India Technology™";
  LinearLayout root=base();topBar(root,"Offer Letter");
  ScrollView scroll=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(18),dp(18),dp(18));box.setBackground(bg(white,12));
  TextView h=tv("GREAT INDIA TECHNOLOGY™",18,true);h.setTextColor(Color.rgb(8,42,91));box.addView(h);
  TextView sub=tv("ADVISER OFFER LETTER — DRAFT",14,true);sub.setTextColor(muted);add(box,sub,38,4);
  TextView body=tv(letter.substring(letter.indexOf("Date:")),14,false);body.setPadding(dp(4),dp(12),dp(4),dp(12));box.addView(body);
  scroll.addView(box);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(dp(14),dp(14),dp(14),dp(8));root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  TextView note=tv("Draft only — review and authorize before issuing as an official offer.",12,false);note.setTextColor(muted);note.setPadding(dp(16),dp(6),dp(16),dp(6));root.addView(note);
  TextView pdf=button("DOWNLOAD OFFER LETTER PDF",Color.rgb(8,42,91));add(root,pdf,52,8);pdf.setOnClickListener(v->{offerPdfText=letter;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/pdf");i.putExtra(Intent.EXTRA_TITLE,"GigSathi_Adviser_Offer_Letter_DRAFT.pdf");startActivityForResult(i,714);});
  TextView share=button("SHARE OFFER LETTER DRAFT",green);add(root,share,52,8);share.setOnClickListener(v->shareDocument("GigSathi Adviser Offer Letter Draft",letter));
  setContentView(root);
 }
 void shareDocument(String title,String body){
  Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_SUBJECT,title);i.putExtra(Intent.EXTRA_TEXT,body);startActivity(Intent.createChooser(i,"Share "+title));
 }
 void showInfo(String title,String message){new AlertDialog.Builder(this).setTitle(title).setMessage(message).setPositiveButton("OK",null).show();}
 void deleteAccountConfirm(DocumentSnapshot u){
  new AlertDialog.Builder(this).setTitle("Delete Account?").setMessage("Your GigSathi profile and account will be permanently deleted. This cannot be undone. Continue?").setNegativeButton("CANCEL",null).setPositiveButton("DELETE",(d,w)->{
   String uid=auth.getCurrentUser().getUid();db.collection("users").document(uid).delete().addOnCompleteListener(x->{auth.getCurrentUser().delete().addOnCompleteListener(y->{if(y.isSuccessful()){getSharedPreferences("gigbiz_secure",MODE_PRIVATE).edit().clear().apply();toast("Account deleted.");login();}else toast("For security, please login again and retry account deletion.");});});
  }).show();
 }
 void topBar(LinearLayout r,String title){TextView b=tv("‹  "+title,20,true);b.setTextColor(purple);b.setPadding(dp(14),dp(15),0,dp(15));r.addView(b,new LinearLayout.LayoutParams(-1,dp(60)));b.setOnClickListener(v->{db.collection("users").document(auth.getCurrentUser().getUid()).get().addOnSuccessListener(this::home);});}
 String err(Exception e){return e==null?"Something went wrong":e.getMessage()==null?"Operation failed":e.getMessage();}
}