plugins { id 'com.android.application' }

android {
    namespace 'com.gayangangacoachingcenter.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.gayangangacoachingcenter.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    signingConfigs {
        release {
            storeFile file('../release-keystore.jks')
            storePassword 'android'
            keyAlias 'appcreator'
            keyPassword 'android'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
        }
    }
}
