const { initializeApp } = require('firebase/app');
const { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } = require('firebase/auth');
const { getFirestore, collection, getDocs, getDoc, doc, addDoc, updateDoc, deleteDoc, query, where, serverTimestamp } = require('firebase/firestore');
const { getStorage, ref, uploadBytes, getDownloadURL } = require('firebase/storage');
const cfg = require('./firebase-config');
const fb = initializeApp(cfg); const auth=getAuth(fb); const db=getFirestore(fb); const storage=getStorage(fb); const root=document.getElementById('app');
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css='<style>*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:#f6f7fb;color:#202331}button,input,textarea,select{font:inherit}.top{height:70px;background:#fff;border-bottom:1px solid #ddd;display:flex;align-items:center;padding:0 24px;gap:15px;position:sticky;top:0;z-index:4}.brand{font-size:25px;font-weight:900;color:#6d3abe}.spacer{flex:1}.wrap{max-width:1400px;margin:auto;padding:22px}.nav{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.btn{padding:10px 14px;border:0;border-radius:9px;cursor:pointer;font-weight:700}.primary{background:#6d3abe;color:#fff}.secondary{background:#eee;color:#333}.danger{background:#fee2e2;color:#a11}.success{background:#dcfce7;color:#166534}.panel,.card{background:#fff;border:1px solid #e1e4e9;border-radius:14px;padding:18px;margin-bottom:16px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.form{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.input,.select,.textarea{width:100%;padding:11px;border:1px solid #ccd2dc;border-radius:9px;background:#fff}.textarea{min-height:95px;resize:vertical}.full{grid-column:1/-1}.tablebox{overflow:auto}.table{width:100%;border-collapse:collapse;min-width:850px}.table th,.table td{padding:10px;border-bottom:1px solid #eee;text-align:left;vertical-align:top}.thumb{width:50px;height:50px;object-fit:cover;border-radius:9px}.muted{color:#737783;font-size:13px}.login{max-width:420px;margin:90px auto;background:#fff;padding:30px;border-radius:18px;border:1px solid #ddd}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}.form{grid-template-columns:1fr}}@media(max-width:600px){.grid{grid-template-columns:1fr}.wrap{padding:12px}}</style>';
let current='dashboard';
const nav=[['dashboard','📊 Dashboard'],['projects','📁 Projects'],['gigs','💼 Gigs'],['services','🛠 Services'],['categories','🗂 Categories'],['workers','👥 Workers'],['applications','📋 Applications'],['leads','🎯 Leads'],['tasks','✅ Tasks'],['withdrawals','💰 Withdrawals']];
function login(msg=''){root.innerHTML=css+'<div class="login"><div class="brand">GIGBIZ</div><h1>Admin Control Center</h1><p class="muted">Windows Admin App — Admin only</p><input id="email" class="input" placeholder="Admin email"><input id="pass" class="input" type="password" placeholder="Password"><br><button class="btn primary" onclick="doLogin()">LOGIN</button><p id="err" style="color:#b42318">'+esc(msg)+'</p></div>';}
window.doLogin=async()=>{const emailEl=document.getElementById('email'),passEl=document.getElementById('pass'),errEl=document.getElementById('err');try{errEl.textContent='Signing in...';await signInWithEmailAndPassword(auth,emailEl.value.trim(),passEl.value)}catch(e){errEl.textContent=e.message}};
function shell(body){let n=nav.map(x=>'<button class="btn '+(current===x[0]?'primary':'secondary')+'" onclick="go(\''+x[0]+'\')">'+x[1]+'</button>').join('');root.innerHTML=css+'<div class="top"><div class="brand">GIGBIZ ADMIN</div><div class="spacer"></div><span class="muted">'+esc(auth.currentUser?.email||'')+'</span><button class="btn danger" onclick="logout()">Logout</button></div><div class="wrap"><div class="nav">'+n+'</div>'+body+'</div>';}
window.logout=()=>signOut(auth);
window.go=async id=>{current=id;try{await (({dashboard,projects,gigs,services,categories,workers,applications,leads,tasks,withdrawals}[id])||dashboard)()}catch(e){console.error(e);alert('Module error: '+(e?.message||e))}};
async function admin(){if(!auth.currentUser)return login();const u=await getDoc(doc(db,'users',auth.currentUser.uid));if(!u.exists()||u.data().role!=='admin'){await signOut(auth);return login('This account is not an Admin.')}dashboard();}
async function count(c){try{return(await getDocs(collection(db,c))).size}catch(e){return 0}}
async function dashboard(){current='dashboard';const a=[['users','👥','Users'],['projects','📁','Projects'],['gigs','💼','Gigs'],['services','🛠','Services'],['applications','📋','Applications'],['leads','🎯','Leads'],['tasks','✅','Tasks'],['withdrawals','💰','Withdrawals']];let h='';for(const x of a)h+='<div class="card"><div>'+x[1]+'</div><div class="muted">'+x[2]+'</div><h2>'+await count(x[0])+'</h2></div>';shell('<h1>Gigbiz Admin Dashboard</h1><p class="muted">Manage workers, projects, gigs, services, leads, tasks and withdrawals.</p><div class="grid">'+h+'</div>')}
const val=id=>document.getElementById(id)?.value?.trim()||'';
async function upload(){const f=document.getElementById('logoFile')?.files?.[0];if(!f)return '';const r=ref(storage,'gigbiz/logos/'+Date.now()+'_'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_'));await uploadBytes(r,f);return getDownloadURL(r)}
function form(fields,save){let h='<div class="panel"><h2>Add New</h2><div class="form">';fields.forEach(f=>{let id=f[0],lab=f[1],type=f[2]||'text';if(type==='textarea')h+='<div class="full"><label class="muted">'+lab+'</label><textarea id="'+id+'" class="textarea"></textarea></div>';else h+='<div><label class="muted">'+lab+'</label><input id="'+id+'" class="input" type="'+type+'"></div>'});h+='<div class="full"><label class="muted">Logo / image</label><input id="logoFile" class="input" type="file" accept="image/*"></div></div><br><button class="btn primary" onclick="'+save+'()">SAVE</button></div>';return h}
function table(title,headers,rows){let h='<div class="panel"><h2>'+title+'</h2><div class="tablebox"><table class="table"><tr>'+headers.map(x=>'<th>'+x+'</th>').join('')+'</tr>';rows.forEach(r=>h+='<tr>'+r.map(x=>'<td>'+x+'</td>').join('')+'</tr>');return h+'</table></div></div>'}
async function projects(){current='projects';let s=await getDocs(collection(db,'projects')),rows=[];s.forEach(d=>{let x=d.data();rows.push([x.logoUrl?'<img class="thumb" src="'+esc(x.logoUrl)+'">':'—','<b>'+esc(x.title)+'</b><div class="muted">'+esc(x.client)+'</div>',esc(x.workerId),esc(x.applyUrl||''),'<button class="btn danger" onclick="del(\'projects\',\''+d.id+'\')">Delete</button>'])});shell('<h1>Projects</h1>'+form([['title','Project title'],['description','Description','textarea'],['client','Client'],['workerId','Worker ID'],['link','Project link'],['applyUrl','Customer final URL after submit']],'addProject')+table('All Projects',['Logo','Project','Worker','Final URL','Action'],rows))}
window.addProject=async()=>{try{let logoUrl=await upload();await addDoc(collection(db,'projects'),{title:val('title'),description:val('description'),client:val('client'),workerId:val('workerId'),link:val('link'),applyUrl:val('applyUrl'),logoUrl,status:'active',createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});alert('Project added');projects()}catch(e){alert(e.message)}};
async function gigs(){current='gigs';let s=await getDocs(collection(db,'gigs')),rows=[];s.forEach(d=>{let x=d.data();rows.push([x.logoUrl?'<img class="thumb" src="'+esc(x.logoUrl)+'">':'—','<b>'+esc(x.title)+'</b>', '₹'+esc(x.pay||'0'),esc(x.location||''),esc(x.applyUrl||''),'<button class="btn danger" onclick="del(\'gigs\',\''+d.id+'\')">Delete</button>'])});shell('<h1>Gigs / Jobs</h1>'+form([['title','Gig title'],['description','Description','textarea'],['pay','Pay'],['location','Location'],['category','Category'],['serviceId','Service ID'],['applyUrl','Customer final URL after submit']],'addGig')+table('All Gigs',['Logo','Gig','Pay','Location','Final URL','Action'],rows))}
window.addGig=async()=>{try{let logoUrl=await upload();await addDoc(collection(db,'gigs'),{title:val('title'),description:val('description'),pay:val('pay'),location:val('location'),category:val('category'),serviceId:val('serviceId'),applyUrl:val('applyUrl'),logoUrl,status:'active',createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});alert('Gig added');gigs()}catch(e){alert(e.message)}};
async function services(){current='services';let s=await getDocs(collection(db,'services')),rows=[];s.forEach(d=>{let x=d.data();rows.push([x.logoUrl?'<img class="thumb" src="'+esc(x.logoUrl)+'">':'—','<b>'+esc(x.name)+'</b>',esc(x.category||''),esc(x.price||''),'<button class="btn danger" onclick="del(\'services\',\''+d.id+'\')">Delete</button>'])});shell('<h1>Services</h1>'+form([['name','Service name'],['description','Description','textarea'],['category','Category'],['price','Price / earning']],'addService')+table('All Services',['Logo','Service','Category','Price','Action'],rows))}
window.addService=async()=>{try{let logoUrl=await upload();await addDoc(collection(db,'services'),{name:val('name'),description:val('description'),category:val('category'),price:val('price'),logoUrl,status:'active',createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});alert('Service added');services()}catch(e){alert(e.message)}};
async function categories(){current='categories';let s=await getDocs(collection(db,'categories')),rows=[];s.forEach(d=>{let x=d.data();rows.push([esc(x.icon||'📂'),'<b>'+esc(x.name)+'</b>',esc(x.description||''),'<button class="btn danger" onclick="del(\'categories\',\''+d.id+'\')">Delete</button>'])});shell('<h1>Categories</h1>'+form([['name','Category name'],['icon','Icon'],['description','Description','textarea']],'addCategory')+table('All Categories',['Icon','Category','Description','Action'],rows))}
window.addCategory=async()=>{try{await addDoc(collection(db,'categories'),{name:val('name'),icon:val('icon'),description:val('description'),status:'active',createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});alert('Category added');categories()}catch(e){alert(e.message)}};
async function workers(){current='workers';let s=await getDocs(query(collection(db,'users'),where('role','==','worker'))),rows=[];s.forEach(d=>{let x=d.data();rows.push(['<b>'+esc(x.name||'Worker')+'</b>',esc(x.phone||''),esc(x.email||''),esc(x.status||'active'),'<button class="btn success" onclick="workerStatus(\''+d.id+'\',\'active\')">Active</button> <button class="btn danger" onclick="workerStatus(\''+d.id+'\',\'blocked\')">Block</button>'])});shell('<h1>Workers</h1>'+table('Worker Accounts',['Worker','Mobile','Email','Status','Actions'],rows))}
window.workerStatus=async(id,status)=>{try{await updateDoc(doc(db,'users',id),{status});workers()}catch(e){alert(e.message)}};
async function applications(){current='applications';let s=await getDocs(collection(db,'applications')),rows=[];s.forEach(d=>{let x=d.data();rows.push([esc(x.workerEmail||x.workerId||''),esc(x.gigTitle||x.gigId||''),esc(x.status||'pending'),'<button class="btn success" onclick="appStatus(\''+d.id+'\',\'approved\')">Approve</button> <button class="btn danger" onclick="appStatus(\''+d.id+'\',\'rejected\')">Reject</button>'])});shell('<h1>Applications</h1>'+table('Applications',['Worker','Gig','Status','Actions'],rows))}
window.appStatus=async(id,status)=>{try{await updateDoc(doc(db,'applications',id),{status,updatedAt:serverTimestamp()});applications()}catch(e){alert(e.message)}};
async function leads(){current='leads';let s=await getDocs(collection(db,'leads')),rows=[];s.forEach(d=>{let x=d.data();rows.push([esc(x.name||x.customerName||''),esc(x.phone||x.mobile||''),esc(x.pincode||''),esc(x.workerId||''),esc(x.status||'new'),'<button class="btn primary" onclick="leadStatus(\''+d.id+'\',\'converted\')">Converted</button>'])});shell('<h1>Leads</h1>'+table('Customer Leads',['Name','Mobile','Pincode','Worker','Status','Action'],rows))}
window.leadStatus=async(id,status)=>{try{await updateDoc(doc(db,'leads',id),{status,updatedAt:serverTimestamp()});leads()}catch(e){alert(e.message)}};
async function tasks(){current='tasks';let s=await getDocs(collection(db,'tasks')),rows=[];s.forEach(d=>{let x=d.data();rows.push([esc(x.title||x.name||''),esc(x.workerId||''),esc(x.status||'pending'),'<button class="btn success" onclick="taskStatus(\''+d.id+'\',\'completed\')">Complete</button>'])});shell('<h1>Tasks</h1><div class="panel"><input id="taskTitle" class="input" placeholder="Task title"><input id="taskWorker" class="input" placeholder="Worker ID"><textarea id="taskDesc" class="textarea" placeholder="Description"></textarea><br><button class="btn primary" onclick="addTask()">ADD TASK</button></div>'+table('Tasks',['Task','Worker','Status','Action'],rows))}
window.addTask=async()=>{try{await addDoc(collection(db,'tasks'),{title:val('taskTitle'),workerId:val('taskWorker'),description:val('taskDesc'),status:'pending',createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});tasks()}catch(e){alert(e.message)}};
window.taskStatus=async(id,status)=>{try{await updateDoc(doc(db,'tasks',id),{status,updatedAt:serverTimestamp()});tasks()}catch(e){alert(e.message)}};
async function withdrawals(){current='withdrawals';let s=await getDocs(collection(db,'withdrawals')),rows=[];s.forEach(d=>{let x=d.data();rows.push([esc(x.workerId||''),'₹'+esc(x.amount||'0'),esc(x.upiId||x.paymentDetail||''),esc(x.status||'pending'),'<button class="btn success" onclick="wdStatus(\''+d.id+'\',\'approved\')">Approve</button> <button class="btn danger" onclick="wdStatus(\''+d.id+'\',\'rejected\')">Reject</button>'])});shell('<h1>Withdrawals</h1>'+table('Withdrawal Requests',['Worker','Amount','Payment','Status','Actions'],rows))}
window.wdStatus=async(id,status)=>{try{await updateDoc(doc(db,'withdrawals',id),{status,processedAt:serverTimestamp(),processedBy:auth.currentUser.uid});withdrawals()}catch(e){alert(e.message)}};
window.del=async(c,id)=>{if(!confirm('Delete this record?'))return;try{await deleteDoc(doc(db,c,id));go(current)}catch(e){alert(e.message)}};
onAuthStateChanged(auth,u=>u?admin():login());